/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CriaConsultaModal: typeof import('./src/components/app/CriaConsultaModal.vue')['default']
    CriaHorarioModal: typeof import('./src/components/app/CriaHorarioModal.vue')['default']
    EventoModal: typeof import('./src/components/app/HorarioModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HorarioModal: typeof import('./src/components/app/HorarioModal.vue')['default']
    NovoEventoModal: typeof import('./src/components/app/CriaHorarioModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/app/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/app/Spinner.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Toasts: typeof import('./src/components/Toast.vue')['default']
  }
}
