version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Vox/Dockerfile
    ports:
      - "5054:8080"
    environment:
      - JWT_SECRET=MINHA_CHAVE_SUPER_SECRETA_DE_32_BYTES_PARA_HMAC
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=vox_db;Username=postgres;Password=root
      - ConnectionStrings__Redis=redis:6379
    volumes:
    - ./backend:/src

    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: vox_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    networks:
      - app-network
    volumes:
      - redis_data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5054/api
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
